### ISSUE TITLE
can we update the version of swagger ui?

### ISSUE THREAD

**Issue by dfeinzeig** [dtkav/swagger_ui_bundle#11]
it's at 3.25.3

**Comment by gvergine** [comment]
I made a pull request (https://github.com/dtkav/swagger_ui_bundle/pull/13) for updating to 3.28.0, since has a nice fix for multiple file upload

**Comment by dfeinzeig** [comment]
haha, i did the same :D

https://github.com/dtkav/swagger_ui_bundle/pull/12

**Comment by dtkav** [comment]
closed by #14
