### ISSUE TITLE
How to call initOAuth

### ISSUE THREAD

**Issue by FrankCRoth** [dtkav/swagger_ui_bundle#29]
I would like to call the initOAuth method for swagger like outlined here: [OAuth 2.0 configuration](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/). But I don't know how to call it from SWAGGER_UI_CONFIG. 
Could it be possible to get an example how to call the method.

**Comment by DrizzutoJr** [comment]
Any update on this?  I am also very interested because the application will use the same client secret and client id every time

**Comment by RobbeSneyders** [comment]
You can set the arguments as follows and it will be called using those arguments:

```python
SWAGGER_UI_CONFIG = {
    "cinitOauth": {
        "clientId": "your-client-id",
        "clientSecret": "your-client-secret-if-required",
        "realm": "your-realms",
        "appName": "your-app-name",
        "scopeSeparator": " ",
        "scopes": "openid profile",
        "additionalQueryStringParams": {test: "hello"},
        "useBasicAuthenticationWithAccessCodeGrant": true,
        "usePkceWithAuthorizationCodeGrant": true
    }
}
```
