### ISSUE TITLE
Make page title a configuration option

### ISSUE THREAD

**Issue by annabarnes1138** [dtkav/swagger_ui_bundle#6]
Right now the page title simply says "Swagger UI". It would be nice to be able to customize this based on a passed in parameter or possibly just use the title from the spec file

**Comment by dtkav** [comment]
Hey @stecky , sorry for the delayed response.

I've added a jinja variable called `title` that can set the page title in the v0.0.6 release.

I'm assuming you're using this package from within connexion?
AFAIK connexion does not currently have support for passing arbitrary jinja context to the swagger-ui endpoint, so you'll likely have to do something custom.

I'd recommend using your own custom swagger-ui release and passing connexion the `swagger_path` option to specify the path to your swagger-ui directory.
