### ISSUE TITLE
redirect_url when using oauth2 is wrong.

### ISSUE THREAD

**Issue by varunmittal91** [dtkav/swagger_ui_bundle#7]
If the server is running at http://localhost:8080/ with ui at http://localhost:8080/ui/

The redirect path is always http://localhost:8080/oauth2-redirect.htm.

In swagger-ui-3.22.3/swagger-ui-bundle.js
line #71: The redirect uri is generated as such: window.location.host+"/oauth2-redirect.html

This should be instead, window.location.host+window.location.pathname+"/oauth2-redirect.html

**Comment by dtkav** [comment]
hey @varunmittal91 - sorry for the delayed response. This project bundles up the released swagger-ui distribution and packages it for use in pip (mainly for the connexion project). I don't make any changes to the swagger-ui source, (except for including a jinja-renderable index file which allows some variables to be passed in).

If you are still having the issue, it might make sense to check-in with the upstream project (swagger-ui).
