### ISSUE TITLE
Update to latest Swagger UI

### ISSUE THREAD

**Issue by NielsHeltner** [dtkav/swagger_ui_bundle#8]
Would it be possible to update to the latest version of Swagger UI?

**Comment by ramenjosh** [comment]
Bump - the latest version of swagger-ui (3.24.2) contains some security patches that should be included here too. @dtkav is there any chance you could add a contributors guide to the repo? I'd be more than happy to put in a PR for the version bump if there was a guide on how to do so.

**Comment by dtkav** [comment]
Hey folks, I've bumped swagger-ui to 3.24.2
For contributing, it's somewhat complicated at the moment -

The process for bumping the version is something like this:
1. download and extract the latest release
2. copy index.html -> index.j2 and manually add in options that can be populated by jinja templating
3. change variable names / paths in `swagger_ui_bundle/__init__.py`
4. bump the version in `swagger_ui_bundle/__init__.py`

Unfortunately step 2 is pretty manual at the moment, and I can't think of a way to automate it easily.
