### ISSUE TITLE
Add support for OAuth 2.0 configuration

### ISSUE THREAD

**Issue by m-agel** [dtkav/swagger_ui_bundle#9]
Hi @dtkav 

It would be great if we had a way to pass [OAuth 2.0 configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md) to SwaggerUIBundle (v3) - adding these lines to [index.j2 (v3)](https://github.com/dtkav/swagger_ui_bundle/blob/56e06769de47f9d748bdc01ea2121f36cd26052e/swagger_ui_bundle/vendor/swagger-ui-3.24.2/index.j2#L59) should do the trick:

```
      {% if initOAuth is defined %}
      ui.initOAuth(
        {{ initOAuth|tojson|safe }}
      )
      {% endif %}
```
You could then simply pass an appropriate dict named `initOAuth` to `render_template()`, eg.
```python
render_template(
    'index.j2',
    initOAuth={
        'clientId': 'my-swagger-ui',
        'usePkceWithAuthorizationCodeGrant': True,
    }
)
```

This should also be possible in v2 by replacing the [corresponding function call](https://github.com/dtkav/swagger_ui_bundle/blob/56e06769de47f9d748bdc01ea2121f36cd26052e/swagger_ui_bundle/vendor/swagger-ui-2.2.10/index.j2#L58) with the template above (but I haven't tested).

Could you add this in a next release?

**Comment by dtkav** [comment]
Thanks for the idea. Sorry for the delayed response - hopefully this is still useful for you.
